version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    # ports:
    #   - "5000:5000"
    command: node app.js
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password