version: "3"
services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo-db: